import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

const outfitFont = Outfit({
  subsets: ["latin"]
});

export const metadata = {
  title: "pixgen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfitFont.className}  h-full antialiased`}
    >
      <body >
        <Navbar />
        <main className="max-w-7xl mx-auto px-4">{children}</main>
        
        <Footer />
        </body>
    </html>
  );
}
